ForwardList:
  Accounts:
    QQ: 12213312
    Telegram: 12321312
  Topology:
    - From: QQ
      FromChat: 1123131231
      To: Telegram
      ToChat: 31231212344
      ForwardType: ReplyOnly
      # OneWay:
      # Forward from "FromChat" to "ToChat"
      # BiDirection:
      # Forward from "FromChat" to "ToChat" and vise versa
      # ReplyOnly:
      # Forward from "FromChat" to "ToChat", ignoring message without "reply_to"
Driver:
  QQ:
    Account: 643503161
    APIRoot: http://127.0.0.1:5700/
    ListenIP: 172.17.0.1
    ListenPort: 8080
    Token: very
    Secret: long
    IsPro: yes
    ChatList:
      1123131231: group       # lower case
      1234423423: private
      213124432432: discuss
  Telegram:
    BotToken: asdasdsadsadsadsad
DataRoot: /root/coolq/data/image
CommandStart: "!!"

